import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SoLuna Cosmetics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="home-bg h-screen w-full md:px-4 lg:px-8 xl:px-12 p-0 md:py-4 flex flex-col justify-center items-center overflow-hidden">
          <div className="w-full h-full md:rounded-3xl relative flex flex-col justify-center items-center border border-[#0d0d0d] overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
